name: Run commands when issues are opened

on:
  issues:
    types: [opened]

concurrency:
  group: issue-opened-${{ github.event.issue.number }}

permissions:
  contents: read
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.repository == 'researchstation/SHRunner'
    steps:

      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Install Actions
        run: echo "hola"
